
package com.example.storenexdoor;


import java.util.Arrays;
import java.util.List;


import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;
public class Search extends Activity {
	String smartphone = "Nokia Lumia 520 (Black),Sony Xperia C (Black),Nokia Lumia 520 (White),Micromax Canvas Turbo A250 (Blue),Micromax Canvas Magnus A117 (White),Sony Xperia M (Dual SIM- Black),Xolo A500s (Blue),Xolo A500s (Black),Sony Xperia C (White),Karbonn A6 (Black-White),Micromax Canvas 2 Plus A110Q (Black),Nokia Lumia 625 (Black),Sony Xperia M (Single SIM - Black),Sony Xperia M (Dual SIM -White),Sony Xperia M (Dual SIM -Purple),Micromax Canvas Doodle 2 A240 (White),Micromax Bolt A40 (Grey),Nokia Lumia 520 (Yellow),Nokia Lumia 520 (Cyan),HTC Desire U T327W (Dual SIM - Stealth Black),Xolo Q1000s (Black),Micromax Canvas Fun A74 (Midnight Black),Sony Xperia M (Single SIM-White),Micromax Canvas 4 (Grey),Sony Xperia E C1604 (Dual SIM - Black),Micromax Canvas 4 (White)";
	String tablet = "Lenovo Ideatab A1000 Tablet (WiFi, Voice Calling), Black,Lenovo A3000-H Tablet (WiFi, 3G, Voice Calling), Black,Hcl ME Tab V2 Connect 2G Tablet (WiFi, 3G via Dongle, Voice Calling), Silver,Micromax Canvas Tab P650 Tablet (WiFi, 3G, Voice Calling), White,Apple iPad Mini (White-Silver, WiFi, 16GB),3 SM-T211 Tablet with Bluetooth Headset (7-inch, WiFi, 3G, Voice Calling), White,iBall Slide 6318i Tablet (WiFi, 3G via Dongle), White,Apple iPad with Retina Display (White, 16GB, WiFi + Cellular),HCL ME Connect V3 Tablet (WiFi, Voice Calling), Silver,iBall Slide 3G 7271 Tablet (WiFi, 3G, Voice Calling),Lenovo Yoga 8 Tablet (WiFi, 3G, Voice Calling, 16GB),iBall Slide i9018 Tablet (WiFi, 3G via Dongle),HCL ME Connect 3G 2.0 Tablet (WiFi, 3G, Voice Calling),HCL ME Sync 1.0 (U3) Tablet (WiFi, 3G via Dongle),Apple iPad with Retina Display (Black, 16GB, WiFi + Cellular),Xolo QC800 Tablet (WiFi, 3G, Voice Calling), White,iBall Slide 3G 9728 Tablet (WiFi, 3G, Voice Calling),Apple iPad with Retina Display (White, 16GB, WiFi),Apple iPad with Retina Display (Black, WiFi, 16GB),Karbonn TA-Fone A37 HD Tablet (3G, WiFi, Voice Calling), White,HCL ME Champ Tablet (WiFi, 3G via Dongle),Micromax Funbook P255 Tablet (WiFi, 3G via Dongle), Black";
	String laptop = "Dell Inspiron 15 3537 W560351IN9 15.6-inch Laptop (Black ),Lenovo G510 59-382826 (Corei5 4th Gen/ 4GB RAM /500GB HDD/15.6&quot;/Win8),HP Envy 15-j001tx 15.6-inch Laptop,HP Envy 15-J049TX 15.6-inch Laptop (Natural Silver),Dell XPS 12 Ultrabook W562001IN9 12.5-inch Touchsreen Laptop (Anodized Aluminum ),HP 1000 1401AU 14-inch Laptop (Glossy Black),HP 2000-2d03TU 15.6-inch Laptop,HP Pavilion TS 11-E006AU 11.6-inch Laptop (Silver),Lenovo Ideapad S210T 11.6-inch (Black),Toshiba Satellite C50-A P0013 15.6-inch Laptop (Shining Silver),HP Pavilion 15-n010tx 15.6-inch Laptop,HP 2000-2d50TU 15.6-inch Laptop,HP Pavilion 15-n020tu 15.6-inch Laptop,Toshiba Satellite U940-X0110 14-inch Laptop (Ice Silver with Woven Texture),Asus S56CA-XX056H,Lenovo Ideapad S210T 11.6-inch (Black),Samsung NP350V5C-A03IN 15.6inch Titan Silver Laptop(2.6 GHZ Core i5 Processor DDR3 4GB RAM 750 GB Hard Drive Windows8...,HP Pro 450 Laptop 2nd Gen Core i3 2GB RAM 500GB HDD Win8 Pro 14 inch Screen,Acer E1-531 15.6-inch Laptop (Glossy Black),Lenovo G580 15.6-inch Laptop (Black),Toshiba Satellite L40-A I0110 14-inch Laptop (White),Asus VivoBook F202E-CT148H 11.6-inch Laptop (Champagne Gold),Lenovo Essential G585 15.6-inch Laptop (Black),Lenovo G500 59383016 3rd Gen Intel Core i3 4GB RAM 500GB HDD Win8 2GB Graphics 15.6 inch Screen,Dell Inspiron 11 3000 Series W560359IN9 11.6-inch Touchscreen Laptop (Silver ),Dell Inspiron 15 3521 15.6-inch Laptop (Black)";
	String camera = "Nikon D3100 14.2MP Digital SLR Camera (Black) with AF-S 18-55mm VR Kit Lens, 4GB Card, Camera Bag,Nikon D5100 16.2MP Digital SLR Camera (Black) with AF-S 18-55mm VR Lens, 4GB Card, Camera Bag,Nikon D3200 24.2MP Digital SLR Camera (Black) with AF-S 18-55mm VR Kit Lens, 4GB Card, Camera Bag,Canon EOS 600D (EF-S 18-55IS II &amp; EF-S 55-250IS II) Combo Kit with 8GB Card and Camera Bag,Canon EOS 1100D 12.2MP Digital SLR Camera (Gray) with EF-S 18-55 IS II Lens, 8GB SD Card, Camera Bag,Nikon D90 12.3MP Digital SLR Camera (Black) with AF-S 18-105mm VR Lens, 4GB Card, Camera Bag,Nikon D5200 24.1MP Digital SLR Camera (Black) with AF-S 18-55 mm VR Kit Lens, 4GB Card, Camera Bag,Canon EOS 1100D 12.2MP Digital SLR Camera (Black) with EF-S 18-55 IS + EF-S 55-250 IS Twin Lens Kit, 4GB SD Card...,Canon EOS 60D 18MP Digital SLR Camera Body Only (Black) with 4GB Card,Nikon D7000 16.2MP Digital SLR Camera (Black) with AF-S 18-105mm VR Kit Lens, 4GB Card, Camera Bag,Nikon D3200 24.2MP Digital SLR Camera (Black) with 18-105mm VR Kit Lens, 4GB Card, Camera Bag,Nikon D3200 24.2MP Digital SLR Camera Body Only (Black) with 4GB Card, Camera Bag,Sony SLT-A37K 16MP Digital SLR Camera (Black) with Camera Bag,Canon EOS 700D 18MP Digital SLR Camera (Black) with 18-55 STM Lens, 4GB SD Card, Camera Bag,Nikon D5100 16.2MP Digital SLR Camera Body Only (Black) with 4GB Card, Camera Bag,Canon EOS 6D 20.2MP Digital SLR Camera (Black) with 24-105mm IS Lens Kit, Camera Bag,Nikon D7100 24.1MP Digital SLR Camera Body Only (Black) with 4GB Card, Camera Bag,Sony Alpha ILCE-3000 Mirrorless Digital SLR Camera (Black) with 20.1 Megapixel, Bag,Canon EOS 5D Mark 3 22.3MP Digital SLR Camera (Black) with 24-105mm Lens,Nikon D7000 16.2MP Digital SLR Camera Body Only (Black) with 4GB Card, Camera Bag,Nikon D3100 Kit 14.2MP Digital SLR Camera (Black) with 4GB Card, Camera Bag,Nikon D3200 24.2MP Digital SLR camera (Red) with AF-S 18-55mm VR Kit Lens, 4GB Card, Camera Bag,Sony Alpha A58M 20.1MP Digital SLT Camera with SAL18135 Lens (Black)";
	String watche = "Diesel Analog Black Dial Men's Watch - DZ4180,CAT Active Ocean Mens Chronograph Watch - D2.143.21.137,Fossil Dean Chronograph Black Dial Men's Watch - FS4542,Fossil Diamond Analog Black Dial Men's Watch - FS4159,Fossil Arkitekt Analog Black Dial Men's Watch - FS4156,Fossil Analog Black Dial Men's Watch - ME1126,Citizen Eco-Drive Analog Black Dial Men's Watch - CA0021-02E,Casio Edifice Chronograph Black Dial Men's Watch - ERA-200DB-1AVDR (EX106),Fossil Chronograph Multi-Color Dial Men's Watch - ME3028,Maxima Analog White Dial Men's Watch - E-20880L-INST,Casio Outdoor Digital Black Dial Men's Watch - PRG-240T-7DR (SL49),Titan Edge Analog White Dial Men's Watch - 1296SM01,Citizen Eco-Drive Analog Black Dial Men's Watch - CA0341-52E,Citizen Eco-Drive Analog Brown Dial Men's Watch - AT0555-18X,KILLER Black Dial Men's Watch KLW011A,Casio Edifice Analog Black Dial Men's Watch - &nbsp;EF-130D-1A2VDF (ED417),Tommy Hilfiger Analog Blue Dial Men's Watch - TH1790903/D,Fastrack Analog Black Dial Men's Watch - NC3054SL01,Casio Edifice Tachymeter Analog Multi-Color Dial Men's Watch - EF-539D-1AVDF (ED369),Citizen Eco-Drive Analog Beige Dial Men's Watch - BL7110-60P,Fossil Chronograph Black Dial Men's Watch - CH2586,Timex Fashion Multi Function Chronograph Silver Dial Men's Watch M202,Casio Enticer Chronograph Black Dial Men's Watch - BEM-506GL-1AVDF (BS124),Titan Orion Analog White Dial Men's Watch - 1490WL02,Casio Enticer Analog White Dial Men's Watch - MTP-1192E-7ADF (A166),Fossil Grant Chronograph Black Dial Men's Watch - FS4832,Casio Enticer Analog Brown Dial Men's Watch - MTP-1356L-9AVDF (A727),Casio Youth Digital Digital Grey Dial Men's Watch - AE-1000W-1AVDF (D080),Maxima Attivo Analog Black Dial Men's Watch - 26833CMGI,Casio Edifice Tachymeter Analog White Dial Men's Watch - EF-546D-7AVDF (ED398),Timex E-Class Analog Black Dial Men's Watch - NO07,Casio Edifice Water Resistant Analog Multi-Color Dial Men's Watch - EF-130D-1A5VDF (ED419),Fastrack Analog Black Dial Men's Watch - NE9462AP03J,Timex Analog Black Dial Men's Watch - T45581,Casio G-Shock Analog-Digital Black Dial Men's Watch - &nbsp;GA-100-1A4DR (G272),Fastrack OTS Core Analog Silver Dial Men's Watch - NE9336SL02A,Timex Expedition Analog White Dial Men's Watch - T49824,Maxima Attivo Analog White Dial Men's Watch - 26846LMGI,Casio Youth Combination Analog-Digital Black Dial Men's Watch - AW-80D-1AVDF (AD60),Casio Edifice Analog Black Dial Men's Watch - EF-334D-1AVDF (ED420),Casio Enticer Analog Beige Dial Men's Watch - MTP-1355L-9AVDF (A724),Casio Enticer Analog Black Dial Men's Watch - MRW-200H-1BVDF (A595),Fastrack OTS Explorer Analog Blue Dial Men's Watch - 9462AL01,Fossil Chronograph Black Dial Men's Watch - FS4487,KILLER Black Dial Men's Watch KLW023A,Casio Edifice Analog Black Dial Men's Watch - EFA-119BK-1A,Casio Youth Digital Digital White Dial Men's Watch - W-96H-1BVDF (D054)";
	String headphone = "Diesel Analog Black Dial Men's Watch - DZ4180,CAT Active Ocean Mens Chronograph Watch - D2.143.21.137,Fossil Dean Chronograph Black Dial Men's Watch - FS4542,Fossil Diamond Analog Black Dial Men's Watch - FS4159,Fossil Arkitekt Analog Black Dial Men's Watch - FS4156,Fossil Analog Black Dial Men's Watch - ME1126,Citizen Eco-Drive Analog Black Dial Men's Watch - CA0021-02E,Casio Edifice Chronograph Black Dial Men's Watch - ERA-200DB-1AVDR (EX106),Fossil Chronograph Multi-Color Dial Men's Watch - ME3028,Maxima Analog White Dial Men's Watch - E-20880L-INST,Casio Outdoor Digital Black Dial Men's Watch - PRG-240T-7DR (SL49),Titan Edge Analog White Dial Men's Watch - 1296SM01,Citizen Eco-Drive Analog Black Dial Men's Watch - CA0341-52E,Citizen Eco-Drive Analog Brown Dial Men's Watch - AT0555-18X,KILLER Black Dial Men's Watch KLW011A,Casio Edifice Analog Black Dial Men's Watch - &nbsp;EF-130D-1A2VDF (ED417),Tommy Hilfiger Analog Blue Dial Men's Watch - TH1790903/D,Fastrack Analog Black Dial Men's Watch - NC3054SL01,Casio Edifice Tachymeter Analog Multi-Color Dial Men's Watch - EF-539D-1AVDF (ED369),Citizen Eco-Drive Analog Beige Dial Men's Watch - BL7110-60P,Fossil Chronograph Black Dial Men's Watch - CH2586,Timex Fashion Multi Function Chronograph Silver Dial Men's Watch M202,Casio Enticer Chronograph Black Dial Men's Watch - BEM-506GL-1AVDF (BS124),Titan Orion Analog White Dial Men's Watch - 1490WL02,Casio Enticer Analog White Dial Men's Watch - MTP-1192E-7ADF (A166),Fossil Grant Chronograph Black Dial Men's Watch - FS4832,Casio Enticer Analog Brown Dial Men's Watch - MTP-1356L-9AVDF (A727),Casio Youth Digital Digital Grey Dial Men's Watch - AE-1000W-1AVDF (D080),Maxima Attivo Analog Black Dial Men's Watch - 26833CMGI,Casio Edifice Tachymeter Analog White Dial Men's Watch - EF-546D-7AVDF (ED398),Timex E-Class Analog Black Dial Men's Watch - NO07,Casio Edifice Water Resistant Analog Multi-Color Dial Men's Watch - EF-130D-1A5VDF (ED419),Fastrack Analog Black Dial Men's Watch - NE9462AP03J,Timex Analog Black Dial Men's Watch - T45581,Casio G-Shock Analog-Digital Black Dial Men's Watch - &nbsp;GA-100-1A4DR (G272),Fastrack OTS Core Analog Silver Dial Men's Watch - NE9336SL02A,Timex Expedition Analog White Dial Men's Watch - T49824,Maxima Attivo Analog White Dial Men's Watch - 26846LMGI,Casio Youth Combination Analog-Digital Black Dial Men's Watch - AW-80D-1AVDF (AD60),Casio Edifice Analog Black Dial Men's Watch - EF-334D-1AVDF (ED420),Casio Enticer Analog Beige Dial Men's Watch - MTP-1355L-9AVDF (A724),Casio Enticer Analog Black Dial Men's Watch - MRW-200H-1BVDF (A595),Fastrack OTS Explorer Analog Blue Dial Men's Watch - 9462AL01,Fossil Chronograph Black Dial Men's Watch - FS4487,KILLER Black Dial Men's Watch KLW023A,Casio Edifice Analog Black Dial Men's Watch - EFA-119BK-1A,Casio Youth Digital Digital White Dial Men's Watch - W-96H-1BVDF (D054)";
	String pendrive = "Diesel Analog Black Dial Men's Watch - DZ4180,CAT Active Ocean Mens Chronograph Watch - D2.143.21.137,Fossil Dean Chronograph Black Dial Men's Watch - FS4542,Fossil Diamond Analog Black Dial Men's Watch - FS4159,Fossil Arkitekt Analog Black Dial Men's Watch - FS4156,Fossil Analog Black Dial Men's Watch - ME1126,Citizen Eco-Drive Analog Black Dial Men's Watch - CA0021-02E,Casio Edifice Chronograph Black Dial Men's Watch - ERA-200DB-1AVDR (EX106),Fossil Chronograph Multi-Color Dial Men's Watch - ME3028,Maxima Analog White Dial Men's Watch - E-20880L-INST,Casio Outdoor Digital Black Dial Men's Watch - PRG-240T-7DR (SL49),Titan Edge Analog White Dial Men's Watch - 1296SM01,Citizen Eco-Drive Analog Black Dial Men's Watch - CA0341-52E,Citizen Eco-Drive Analog Brown Dial Men's Watch - AT0555-18X,KILLER Black Dial Men's Watch KLW011A,Casio Edifice Analog Black Dial Men's Watch - &nbsp;EF-130D-1A2VDF (ED417),Tommy Hilfiger Analog Blue Dial Men's Watch - TH1790903/D,Fastrack Analog Black Dial Men's Watch - NC3054SL01,Casio Edifice Tachymeter Analog Multi-Color Dial Men's Watch - EF-539D-1AVDF (ED369),Citizen Eco-Drive Analog Beige Dial Men's Watch - BL7110-60P,Fossil Chronograph Black Dial Men's Watch - CH2586,Timex Fashion Multi Function Chronograph Silver Dial Men's Watch M202,Casio Enticer Chronograph Black Dial Men's Watch - BEM-506GL-1AVDF (BS124),Titan Orion Analog White Dial Men's Watch - 1490WL02,Casio Enticer Analog White Dial Men's Watch - MTP-1192E-7ADF (A166),Fossil Grant Chronograph Black Dial Men's Watch - FS4832,Casio Enticer Analog Brown Dial Men's Watch - MTP-1356L-9AVDF (A727),Casio Youth Digital Digital Grey Dial Men's Watch - AE-1000W-1AVDF (D080),Maxima Attivo Analog Black Dial Men's Watch - 26833CMGI,Casio Edifice Tachymeter Analog White Dial Men's Watch - EF-546D-7AVDF (ED398),Timex E-Class Analog Black Dial Men's Watch - NO07,Casio Edifice Water Resistant Analog Multi-Color Dial Men's Watch - EF-130D-1A5VDF (ED419),Fastrack Analog Black Dial Men's Watch - NE9462AP03J,Timex Analog Black Dial Men's Watch - T45581,Casio G-Shock Analog-Digital Black Dial Men's Watch - &nbsp;GA-100-1A4DR (G272),Fastrack OTS Core Analog Silver Dial Men's Watch - NE9336SL02A,Timex Expedition Analog White Dial Men's Watch - T49824,Maxima Attivo Analog White Dial Men's Watch - 26846LMGI,Casio Youth Combination Analog-Digital Black Dial Men's Watch - AW-80D-1AVDF (AD60),Casio Edifice Analog Black Dial Men's Watch - EF-334D-1AVDF (ED420),Casio Enticer Analog Beige Dial Men's Watch - MTP-1355L-9AVDF (A724),Casio Enticer Analog Black Dial Men's Watch - MRW-200H-1BVDF (A595),Fastrack OTS Explorer Analog Blue Dial Men's Watch - 9462AL01,Fossil Chronograph Black Dial Men's Watch - FS4487,KILLER Black Dial Men's Watch KLW023A,Casio Edifice Analog Black Dial Men's Watch - EFA-119BK-1A,Casio Youth Digital Digital White Dial Men's Watch - W-96H-1BVDF (D054)";
	String printer = "HP Deskjet 1510 Color All-in-One Inkjet Printer,Canon PIXMA MP 287 All-In-One Inkjet Printer,HP Deskjet Ink Advantage 2545 All-in-One Color Printer,Canon PIXMA E510 Color Inkjet Printer,HP DeskJet 1050 All-in-One&nbsp;Color Inkjet Printer,Epson L210 Colour All-in-one Inkjet Printer,Ricoh Aficio SP 1200SF Multi Function Monochrome Laser Printer,Canon PIXMA MG 2570 Multi Function Inkjet Color Printer,HP Laserjet Pro M1216nfh Multi Function Monochrome Laser Printer,HP Deskjet 3515 All-in-One Color Inkjet Printer,HP Deskjet Ink Advantage 1515 Color All-in-One Inkjet Printer,Brother DCP-J140w Wireless Compact Inkjet All-in-One,HP Deskjet 2515 All-in-One Color Inkjet Printer,Canon MX397 Inkjet All in One Printer,HP Deskjet Ink Advantage 3545 e-All-in-One Inkjet Printer,Canon PIXMA MG 3570 Multi Function Inkjet Color Printer (Black),HP Laserjet Pro M1218nfs Multi Function Monochrome Laser Printer,HP Deskjet 3525 All-in-One Color Inkjet Printer,Epson ME Office 960FWD All In One Printer,Canon MX457 Inkjet All in One Wireless Printer,Canon PIXMA MG 3170 Ink All-In-One Printer,HP Deskjet Ink Advantage 4625 All-in-One Printer,Ricoh Aficio SP 100SF Multi Function Monochrome Laser Printer,HP OfficeJet Pro 8600 Plus-e All-in-One Color Printer,Brother MFC 7860DW Printer,HP Officejet Pro 3610 Black and White e-All-in-One Printer";
	String trimmer = "Philips QT4005/15 Beard and Stubble Trimmer (M-Power Play),Panasonic ER-GB30K Men's Trimmer,Philips QG3333/15 Multi Purpose Grooming Kit (M-Power Detailed),Philips QG3320/15 Multi Purpose Trimmer (M-Power Easy),Philips QG3383 Multi Purpose Grooming Kit Trimmer (M-Power Ultimate),Philips QG3343/16 Multi Purpose Trimmer (M-Power Perfect),Panasonic ER206KK Men's Trimmer,Wahl 09971-724 Compact Battery Trimmer,Philips NT9110/30 Nose and Ear Hair Trimmer,Wahl 09916-1024 Beard Rechargeable Trimmer,Philips QT4000/15 Trimmer,Philips HP6382/20 Bikini Trimmer,Wahl 09155-024 Home Pro Basic Hair Cutting Kit Hair Clipper,Philips BG2024/15 Body Groom Shaver,Gillette Fusion ProGlide Styler 3-in-1 Men's Body Groomer with Beard Trimmer,PHILIPS TRIMMER QT 4005/15,Panasonic ER-GY10K 6-in-1 Men's Body Grooming Kit,Remington PG6030 All in One Personal Grooming Kit,Wahl 1541-0010 Lithium Ion Vario Stubble Trimmer,Remington MPT3000 Smooth and Silky Detail Trimmer,Wahl 05640-624 Micro Groomsman Pen Trimmer,Wahl 05640-124 Micro Finish Pen Trimmer,Remington HC70 Hair Clipper,Maxel AK-604B Rechargeable Hair and Beard Trimmer,Wahl Professional Moser 1400-0010 Hair Clipper (Red),Men Hair Trimmer with Charging Clipper";


    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.frinds);
       
        ListView listView1 = (ListView) findViewById(R.id.listView1);
        SharedPreferences sharedpref = getSharedPreferences("Mydata", Context.MODE_PRIVATE);
        final String destination_string = sharedpref.getString("12345","");
        String fina="Search item not in databas..try one of ,smartphone,tablet, laptop, camera, watch, headphone, pendrive, printer, trimmer";
        System.out.println(destination_string);
if(destination_string.equals("smartphone"))fina=smartphone;
else if(destination_string.equals("tablet"))fina=tablet;
else if(destination_string.equals("laptop"))fina=laptop;
else if(destination_string.equals("camera"))fina=camera;
else if(destination_string.equals("watch"))fina=watche;
else if(destination_string.equals("headphone"))fina=headphone;
else if(destination_string.equals("pendrive"))fina=pendrive;
else if(destination_string.equals("printer"))fina=printer;
else if(destination_string.equals("trimmer"))fina=trimmer;

List<String> items = Arrays.asList(fina.split("\\s*,\\s*"));       
ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,
            android.R.layout.simple_list_item_1, items);
       
        listView1.setAdapter(adapter);
    }
}